name: 编译caddy二进制文件

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
jobs:
 check:
  runs-on: ubuntu-latest
  outputs:
    ver: ${{ steps.getversion.outputs.ver }}
    cver: ${{ steps.getversion.outputs.cver }}
  steps:
  - name: 检查更新
    id: getversion
    run: |
      ver=`curl https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name'`
      cver=`curl https://api.github.com/repos/lmq8267/caddy/releases/latest | jq -r '.tag_name'`
      echo "ver=${ver}" >> $GITHUB_OUTPUT
      echo "cver=${cver}" >> $GITHUB_OUTPUT
  -     name: 删除工作流
        uses: GitRML/delete-workflow-runs@main
        with:
         token: ${{ secrets.c8 }}
         retain_days: 2
         keep_minimum_runs: 1
 build: 
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: amd64
            OS: ubuntu-latest
            AARCH: amd64
            OOS: linux
            
          - TARGET: arm64
            OS: ubuntu-latest
            ARCH: arm64
            OOS: linux
            
          - TARGET: mips
            OS: ubuntu-latest
            SOFT: softfloat
            ARCH: mips
            OOS: linux
            
          - TARGET: mips64
            OS: ubuntu-latest
            SOFT: softfloat
            ARCH: mips64
            OOS: linux
            
          - TARGET: mips64le
            OS: ubuntu-latest
            SOFT: softfloat
            ARCH: mips64le
            OOS: linux
            
          - TARGET: mipsel
            OS: ubuntu-latest
            SOFT: softfloat
            ARCH: mipsle
            OOS: linux
            
          - TARGET: ppc64le
            OS: ubuntu-latest
            ARCH: ppc64le
            OOS: linux

          - TARGET: s390x
            OS: ubuntu-latest
            ARCH: s390x
            OOS: linux
            
          - TARGET: arm
            OS: ubuntu-latest
            ARM: 5
            ARCH: arm
            OOS: linux
            
          - TARGET: armv5l
            OS: ubuntu-latest
            ARM: 5
            ARCH: arm
            OOS: linux
            
          - TARGET: armv6
            OS: ubuntu-latest
            ARM: 6
            ARCH: arm
            OOS: linux

          - TARGET: armv7l
            OS: ubuntu-latest
            ARM: 7
            ARCH: arm
            OOS: linux

          - TARGET: freebsd-x86-64
            OS: ubuntu-latest
            ARCH: amd64
            OOS: freebsd
            
    runs-on: ${{ matrix.OS }}
    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      OOS: ${{ matrix.OOS }}
      SOFT: ${{ matrix.SOFT }}
      ARM: ${{ matrix.ARM }}
      ARCH: ${{ matrix.ARCH }}
    steps:
      - name: 获取最新Go
        run: |
          latest_version=$(curl -L -k -s https://golang.org/dl/?mode=json | grep -m 1 -o '"version": "[^"]*' | sed 's/"version": "//' | tr -d 'go" ')
          echo "go版本=$latest_version"
          echo "gotag=$latest_version" >> $GITHUB_ENV
      - name: 安装go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.gotag }}
      -
        name: 检查代码仓库
        uses: actions/checkout@v4
      - name: 安装 UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true
      - 
        name: 编译
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          git clone -b ${{ needs.check.outputs.ver }} https://github.com/caddyserver/caddy /opt/mycaddy
          cp -rf ./browse.html /opt/mycaddy/modules/caddyhttp/fileserver/browse.html
          echo "开始构建"
          mkdir -p /opt/caddy
          cd /opt/caddy
          sudo timedatectl set-timezone "Asia/Shanghai"
          GOOS=${OOS} GOARCH=${ARCH} GOMIPS=${SOFT} GOARM=${ARM} xcaddy build \
          --with github.com/caddyserver/caddy/v2=/opt/mycaddy@${{ steps.getversion.outputs.ver }} \
          --with github.com/mholt/caddy-webdav \
          --with github.com/aksdb/caddy-cgi/v2
          file caddy
          du -k caddy
          mv caddy caddy-${TARGET}
          if [[ $TARGET != mips64 ]] && [[ $TARGET != mips64le ]] && [[ $TARGET != s390x ]] && [[ $TARGET != freebsd-x86-64 ]] ;then
          cp caddy-${TARGET} caddy-${TARGET}-upx
          upx --lzma --best caddy-${TARGET}-upx
          du -k caddy-${TARGET}-upx
          fi
          #sudo apt install qemu-user
          #qemu-mipsel caddy -v
          
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
            token: ${{ secrets.c8 }}
            body: |
             > ### 编译时间 ：${{ env.build_time }}

              caddy-CPU架构-upx 为upx压缩文件
              
              添加了两个插件：
              **[mholt/caddy-webdav](https://github.com/mholt/caddy-webdav)**
              **[aksdb/caddy-cgi](https://github.com/aksdb/caddy-cgi)**

              查看集成的插件列表命令： `caddy list-modules -s`
              
              **[官方更新说明](https://github.com/caddyserver/caddy/releases)**
              
            tag_name: ${{ needs.check.outputs.ver }}
            files: /opt/caddy/*
 keepalive-workflow:
    # github超过60天未提交将自动停止工作流
    name: 工作流保活 
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        #with:
          #use_api: true
      
